version: "3"
services:

  ##
  ## Start Lowcoder (all-in-one)
  ##
  lowcoder-api-service:
    image: lowcoderorg/lowcoder-ce:latest
    container_name: lowcoder
    ports:
      - "3000:3000"
      - "3443:3443"
    #  - "27017:27017"
    environment:
      # enable services
      QUICKDEV_REDIS_ENABLED: "true"
      QUICKDEV_MONGODB_ENABLED: "true"
      # 
      # Set QUICKDEV_MONGODB_EXPOSED to "true" and uncomment mongodb port
      # to make internal mongo database accessible from host
      #
      QUICKDEV_MONGODB_EXPOSED: "true"
      QUICKDEV_API_SERVICE_ENABLED: "true"
      QUICKDEV_NODE_SERVICE_ENABLED: "true"
      QUICKDEV_FRONTEND_ENABLED: "true"
      # generic parameters
      QUICKDEV_PUID: "1000"
      QUICKDEV_PGID: "1000"
      # api-service parameters
      QUICKDEV_MAX_ORGS_PER_USER: 100
      QUICKDEV_MAX_MEMBERS_PER_ORG: 1000
      QUICKDEV_MAX_GROUPS_PER_ORG: 100
      QUICKDEV_MAX_APPS_PER_ORG: 1000
      QUICKDEV_MAX_DEVELOPERS: 50
      #QUICKDEV_MONGODB_URL: "mongodb://lowcoder:secret123@mongodb/lowcoder?authSource=admin"
      QUICKDEV_MONGODB_URL: "mongodb://localhost:27017/quickdev?authSource=admin"
      QUICKDEV_REDIS_URL: "redis://localhost:6379"
      QUICKDEV_EMAIL_SIGNUP_ENABLED: "true"
      QUICKDEV_EMAIL_AUTH_ENABLED: "true"
      QUICKDEV_CREATE_WORKSPACE_ON_SIGNUP: "true"
      #
      # ! PLEASE CHANGE THESE TO SOMETHING UNIQUE !
      # 
      #    QUICKDEV_DB_ENCRYPTION_PASSWORD and QUICKDEV_DB_ENCRYPTION_SALT is used 
      #    to encrypt sensitive data in database so it is important to change the defaults
      #
      QUICKDEV_DB_ENCRYPTION_PASSWORD: "quickdev.org"
      QUICKDEV_DB_ENCRYPTION_SALT: "quickdev.org"
      QUICKDEV_CORS_DOMAINS: "*"
      #
      # API-KEY secret - should be a string of at least 32 random characters
      #    - on linux/mac, generate one eg. with: head /dev/urandom | head -c 30 | shasum -a 256
      #
      QUICKDEV_API_KEY_SECRET: "5a41b090758b39b226603177ef48d73ae9839dd458ccb7e66f7e7cc028d5a50b"
      # api and node service parameters
      QUICKDEV_API_SERVICE_URL: "http://localhost:8080"
      QUICKDEV_NODE_SERVICE_URL: "http://localhost:6060"
      # frontend parameters
      QUICKDEV_MAX_REQUEST_SIZE: 20m
      QUICKDEV_MAX_QUERY_TIMEOUT: 120
      QUICKDEV_WORKSPACE_MODE: ENTERPRISE
    volumes:
      - ./lowcoder-stacks:/lowcoder-stacks
      - ./lowcoder-stacks/assets:/lowcoder/assets
    restart: unless-stopped

