version: "3"
services:

  ##
  ## Start services required for Lowcoder (MongoDB and Redis)
  ##
  mongodb:
    image: "mongo:4.4"
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: lowcoder
      MONGO_INITDB_ROOT_USERNAME: lowcoder
      MONGO_INITDB_ROOT_PASSWORD: secret123
    # Uncomment to save database data into local 'mongodata' folder
    # volumes:
    #   - ./mongodata:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis


  ##
  ## Start Lowcoder backend services (api-service and node-service)
  ##
  lowcoder-api-service:
    image: lowcoderorg/lowcoder-ce-api-service:latest
    container_name: lowcoder-api-service
    # Enabled ports to be able to access backend from host
    # ports:
    #   - "8080:8080"
    environment:
      QUICKDEV_PUID: "9001"
      QUICKDEV_PGID: "9001"
      QUICKDEV_MONGODB_URL: "mongodb://lowcoder:secret123@mongodb/lowcoder?authSource=admin"
      QUICKDEV_REDIS_URL: "redis://redis:6379"
      QUICKDEV_NODE_SERVICE_URL: "http://lowcoder-node-service:6060"
      QUICKDEV_MAX_QUERY_TIMEOUT: 120
      QUICKDEV_EMAIL_AUTH_ENABLED: "true"
      QUICKDEV_EMAIL_SIGNUP_ENABLED: "true"
      QUICKDEV_CREATE_WORKSPACE_ON_SIGNUP: "true"
      #
      # ! PLEASE CHANGE THESE TO SOMETHING UNIQUE !
      # 
      #    QUICKDEV_DB_ENCRYPTION_PASSWORD and QUICKDEV_DB_ENCRYPTION_SALT is used 
      #    to encrypt sensitive data in database so it is important to change the defaults
      #
      QUICKDEV_DB_ENCRYPTION_PASSWORD: "quickdev.org"
      QUICKDEV_DB_ENCRYPTION_SALT: "quickdev.org"
      QUICKDEV_CORS_DOMAINS: "*"
      QUICKDEV_MAX_ORGS_PER_USER: 100
      QUICKDEV_MAX_MEMBERS_PER_ORG: 1000
      QUICKDEV_MAX_GROUPS_PER_ORG: 100
      QUICKDEV_MAX_APPS_PER_ORG: 1000
      QUICKDEV_MAX_DEVELOPERS: 50
      #
      # API-KEY secret - should be a string of at least 32 random characters
      #    - on linux/mac, generate one eg. with: head /dev/urandom | head -c 30 | shasum -a 256
      #
      QUICKDEV_API_KEY_SECRET: "5a41b090758b39b226603177ef48d73ae9839dd458ccb7e66f7e7cc028d5a50b"
      QUICKDEV_WORKSPACE_MODE: ENTERPRISE
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis

  lowcoder-node-service:
    image: lowcoderorg/lowcoder-ce-node-service:latest
    container_name: lowcoder-node-service
    # Enabled ports to be able to access backend from host
    # ports:
    #   - "6060:6060"
    environment:
      QUICKDEV_PUID: "9001"
      QUICKDEV_PGID: "9001"
      QUICKDEV_API_SERVICE_URL: "http://lowcoder-api-service:8080"
    restart: unless-stopped
    depends_on:
      - lowcoder-api-service

  ##
  ## Start Lowcoder web frontend
  ##
  lowcoder-frontend:
    image: lowcoderorg/lowcoder-ce-frontend:latest
    container_name: lowcoder-frontend
    ports:
      - "3000:3000"
    environment:
      QUICKDEV_PUID: "9001"
      QUICKDEV_PGID: "9001"
      QUICKDEV_MAX_REQUEST_SIZE: 20m
      QUICKDEV_MAX_QUERY_TIMEOUT: 120
      QUICKDEV_API_SERVICE_URL: "http://lowcoder-api-service:8080"
      QUICKDEV_NODE_SERVICE_URL: "http://lowcoder-node-service:6060"
    restart: unless-stopped
    depends_on:
      - lowcoder-node-service
      - lowcoder-api-service
    # Uncomment to serve local files as static assets
    # volumes:
    #   - ./static-assets:/lowcoder/assets

