{{- $nameSpace := include "lowcoder.namespace" . -}}
{{- $name := include "lowcoder.fullname" . -}}
{{- $lowcoderDatabase := first .Values.mongodb.auth.databases -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lowcoder.fullname" . }}-api-service
  labels:
    {{- include "lowcoder.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.redis.enabled }}
  QUICKDEV_REDIS_URL: "redis://{{ $name }}-redis-master.{{ $nameSpace }}.svc.cluster.local:6379"
  {{- else }}
  QUICKDEV_REDIS_URL: {{ .Values.redis.externalUrl | quote }}
  {{- end }}
  {{- if .Values.global.config.nodeServiceUrl }}
  QUICKDEV_NODE_SERVICE_URL: {{ .Values.global.config.nodeServiceUrl | quote }}
  {{- else }}
  QUICKDEV_NODE_SERVICE_URL: "http://{{ $name }}-node-service:{{ .Values.nodeService.service.port }}"
  {{- end }}
  QUICKDEV_PUID: {{ .Values.global.config.userId | default "9001" | quote }}
  QUICKDEV_PGID: {{ .Values.global.config.groupId | default "9001" | quote }}
  QUICKDEV_CORS_DOMAINS: {{ .Values.global.config.corsAllowedDomains | default  "*" | quote }}
  QUICKDEV_EMAIL_AUTH_ENABLED: {{ .Values.global.config.enableEmailAuth | default "true" | quote }}
  QUICKDEV_EMAIL_SIGNUP_ENABLED: {{ .Values.global.config.enableUserSignUp | default "true" | quote }}
  QUICKDEV_MAX_QUERY_TIMEOUT: {{ .Values.global.config.maxQueryTimeout | default "120" | quote }}
  QUICKDEV_MAX_ORGS_PER_USER: {{ .Values.global.defaults.maxOrgsPerUser | default "100" | quote }}
  QUICKDEV_MAX_MEMBERS_PER_ORG: {{ .Values.global.defaults.maxMembersPerOrg | default "1000" | quote }}
  QUICKDEV_MAX_GROUPS_PER_ORG: {{ .Values.global.defaults.maxGroupsPerOrg | default "100" | quote }}
  QUICKDEV_MAX_APPS_PER_ORG: {{ .Values.global.defaults.maxAppsPerOrg | default "1000" | quote }}
  QUICKDEV_MAX_DEVELOPERS: {{ .Values.global.defaults.maxDevelopers | default "50" | quote }}
  QUICKDEV_WORKSPACE_MODE: {{ .Values.global.config.workspaceMode | default "SAAS" | quote }}
  QUICKDEV_CREATE_WORKSPACE_ON_SIGNUP: {{ .Values.global.config.createWorkspaceOnSignup | default "true" | quote }}
