{{- $nameSpace := include "lowcoder.namespace" . -}}
{{- $mongoUser := first .Values.mongodb.auth.usernames -}}
{{- $mongoPassword := first .Values.mongodb.auth.passwords -}}
{{- $mongoServicename := .Values.mongodb.service.nameOverride -}}
{{- $lowcoderDatabase := first .Values.mongodb.auth.databases -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lowcoder.fullname" . }}-api-service
  labels:
    {{- include "lowcoder.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  {{- if .Values.mongodb.enabled }}
  QUICKDEV_MONGODB_URL: "mongodb://{{ $mongoUser }}:{{ $mongoPassword }}@{{ $mongoServicename }}.{{ $nameSpace }}.svc.cluster.local/{{ $lowcoderDatabase }}?retryWrites=true&ssl=false"
  {{- else }}
  QUICKDEV_MONGODB_URL: {{ .Values.mongodb.externalUrl | quote }}
  {{- end }}
  QUICKDEV_DB_ENCRYPTION_PASSWORD: {{ .Values.global.config.encryption.password | default "lowcoder.org" | quote }}
  QUICKDEV_DB_ENCRYPTION_SALT: {{ .Values.global.config.encryption.salt | default "lowcoder.org" | quote }}
  QUICKDEV_API_KEY_SECRET: "{{ .Values.global.config.apiKeySecret }}"
