auth:
  api-key:
    secret: ${QUICKDEV_API_KEY_SECRET:5a41b090758b39b226603177ef48d73ae9839dd458ccb7e66f7e7cc028d5a50b}
  email:
    enable: ${QUICKDEV_EMAIL_AUTH_ENABLED:true}
    enable-register: ${QUICKDEV_EMAIL_SIGNUP_ENABLED:true}
  workspace-creation: ${QUICKDEV_CREATE_WORKSPACE_ON_SIGNUP:true}

spring:
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: false
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  codec:
    max-in-memory-size: 20MB
  webflux:
    context-path: /

server:
  compression:
    enabled: true
  forward-headers-strategy: NATIVE
  http2:
    enabled: true
  port: 8080
  shutdown: graceful

default:
  orgs-per-user: ${QUICKDEV_MAX_ORGS_PER_USER:100}
  org-member-count: ${QUICKDEV_MAX_MEMBERS_PER_ORG:1000}
  org-group-count: ${QUICKDEV_MAX_GROUPS_PER_ORG:100}
  org-app-count: ${QUICKDEV_MAX_APPS_PER_ORG:1000}
  developer-count: ${QUICKDEV_MAX_DEVELOPERS:50}
  api-rate-limit: ${QUICKDEV_API_RATE_LIMIT:50}

common:
  cookie-name: QUICKDEV_TOKEN
  product: quickdev
  domain:
    default-value: quickdev.org
  cloud: false
  version: 2.1.4
  apiVersion: 1.1
  block-hound-enable: false
  js-executor:
    host: ${QUICKDEV_NODE_SERVICE_URL:http://127.0.0.1:6060}
  max-query-request-size: ${QUICKDEV_MAX_REQUEST_SIZE:20m}
  max-query-response-size: ${QUICKDEV_MAX_REQUEST_SIZE:20m}
  max-upload-size: ${QUICKDEV_MAX_REQUEST_SIZE:20m}
  max-query-timeout: ${QUICKDEV_MAX_QUERY_TIMEOUT:120}
  workspace:
    mode: ${QUICKDEV_WORKSPACE_MODE:ENTERPRISE}
  marketplace:
    private-mode: ${QUICKDEV_MARKETPLACE_PRIVATE_MODE:false}

material:
  mongodb-grid-fs:
    bucket-name: material