common:
  encrypt:
    password: ${QUICKDEV_DB_ENCRYPTION_PASSWORD:quickdev.org}
    salt: ${QUICKDEV_DB_ENCRYPTION_SALT:quickdev.org}
  security:
    corsAllowedDomainString: ${QUICKDEV_CORS_DOMAINS:*}
  workspace:
    mode: ${QUICKDEV_WORKSPACE_MODE:ENTERPRISE}

spring:
  data:
    mongodb:
      uri: ${QUICKDEV_MONGODB_URL:mongodb://localhost:27017/quickdev?socketTimeoutMS=5000}
    redis:
      url: ${QUICKDEV_REDIS_URL:redis://localhost:6379}
