{{- $nameSpace := include "lowcoder.namespace" . -}}
{{- $name := include "lowcoder.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lowcoder.fullname" . }}-frontend
  labels:
    {{- include "lowcoder.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  QUICKDEV_PUID: {{ .Values.global.config.userId | default "9001" | quote }}
  QUICKDEV_PGID: {{ .Values.global.config.groupId | default "9001" | quote }}
  {{- if .Values.global.config.apiServiceUrl }}
  QUICKDEV_API_SERVICE_URL: {{ .Values.global.config.apiServiceUrl | trimSuffix "/" | quote }}
  {{- else }}
  QUICKDEV_API_SERVICE_URL: "http://{{ $name }}-api-service:{{ .Values.apiService.service.port }}"
  {{- end }}
  {{- if .Values.global.config.nodeServiceUrl }}
  QUICKDEV_NODE_SERVICE_URL: {{ .Values.global.config.nodeServiceUrl | trimSuffix "/" | quote }}
  {{- else }}
  QUICKDEV_NODE_SERVICE_URL: "http://{{ $name }}-node-service:{{ .Values.nodeService.service.port }}"
  {{- end }}
  QUICKDEV_MAX_REQUEST_SIZE: {{ .Values.global.config.maxRequestSize | default "20m" | quote }}
  QUICKDEV_MAX_QUERY_TIMEOUT: {{ .Values.global.config.maxQueryTimeout | default "120" | quote }}

